apiVersion: v1
kind: Service
metadata:
  name: alertmanager-pachka-router
  labels:
    app: alertmanager-pachka-router
spec:
  type: ClusterIP
  selector:
    app: alertmanager-pachka-router
  ports:
    - name: http
      port: 8080
      targetPort: http

